using System.Collections.Generic;
using CustomSettingsAndLayouts;
using Kitchen.Layouts;
using Kitchen.Layouts.Modules;
using KitchenData;
using KitchenLib.Customs;
using KitchenLib.References;
using KitchenLib.Utils;
using ParentsEvent.Customs.RestaurantSettings;
using ParentsEvent.Utilities;
using UnityEngine;

namespace ParentsEvent.Customs.LayoutProfiles
{
    public class ParentsLayout : CustomLayoutProfile
    {
        public override string UniqueNameID => "ParentsLayout";
        public override LayoutGraph Graph => GenerateLayout(UniqueNameID);
        public override int MaximumTables => 3;
        public override List<GameDataObject> RequiredAppliances => GDOReferences.DinerLayout.RequiredAppliances;
        public override GameDataObject Table => GDOReferences.DinerLayout.Table;
        public override GameDataObject Counter => GDOReferences.DinerLayout.Counter;
        public override Appliance ExternalBin => GDOReferences.DinerLayout.ExternalBin;

// This script was generated by Layout Builder
        public static LayoutGraph GenerateLayout(string graphName)
        {
            // Creating the graph

            LayoutGraph graph = ScriptableObject.CreateInstance<LayoutGraph>();

            // Creating all the nodes

            MergeRoomsByType MergeRoomsByType0 = ScriptableObject.CreateInstance<MergeRoomsByType>();
            RecentreLayout RecentreLayout0 = ScriptableObject.CreateInstance<RecentreLayout>();
            CreateFrontDoor CreateFrontDoor0 = ScriptableObject.CreateInstance<CreateFrontDoor>();
            Output Output0 = ScriptableObject.CreateInstance<Output>();
            FindAllFeatures FindAllFeatures0 = ScriptableObject.CreateInstance<FindAllFeatures>();
            FilterByFreeSpace FilterByFreeSpace0 = ScriptableObject.CreateInstance<FilterByFreeSpace>();
            FilterOnePerPair FilterOnePerPair0 = ScriptableObject.CreateInstance<FilterOnePerPair>();
            FilterAdjacentPair FilterAdjacentPair0 = ScriptableObject.CreateInstance<FilterAdjacentPair>();
            FilterByRoom FilterByRoom0 = ScriptableObject.CreateInstance<FilterByRoom>();
            AppendFeatures AppendFeatures0 = ScriptableObject.CreateInstance<AppendFeatures>();
            SwitchFeatures SwitchFeatures0 = ScriptableObject.CreateInstance<SwitchFeatures>();
            RequireAccessible RequireAccessible0 = ScriptableObject.CreateInstance<RequireAccessible>();
            RequireFeatures RequireFeatures0 = ScriptableObject.CreateInstance<RequireFeatures>();
            SplitRooms SplitRooms0 = ScriptableObject.CreateInstance<SplitRooms>();
            CreateRoomByJoins CreateRoomByJoins0 = ScriptableObject.CreateInstance<CreateRoomByJoins>();
            CreateRoomByJoins CreateRoomByJoins1 = ScriptableObject.CreateInstance<CreateRoomByJoins>();
            RoomGrid RoomGrid0 = ScriptableObject.CreateInstance<RoomGrid>();
            AddRoom AddRoom0 = ScriptableObject.CreateInstance<AddRoom>();

            // Setting all the values

            MergeRoomsByType0.FixSeed = 0;
            MergeRoomsByType0.position = new Vector2(-625f, -137);
            RecentreLayout0.FixSeed = 0;
            RecentreLayout0.position = new Vector2(-250f, -137);
            CreateFrontDoor0.Type = RoomType.Dining;
            CreateFrontDoor0.ForceFirstHalf = false;
            CreateFrontDoor0.FixSeed = 0;
            CreateFrontDoor0.position = new Vector2(163f, -187);
            Output0.FixSeed = 0;
            Output0.position = new Vector2(3000f, -150);
            FindAllFeatures0.Feature = FeatureType.Door;
            FindAllFeatures0.FixSeed = 0;
            FindAllFeatures0.position = new Vector2(113f, 438);
            FilterByFreeSpace0.FixSeed = 0;
            FilterByFreeSpace0.position = new Vector2(500f, 163);
            FilterOnePerPair0.FixSeed = 0;
            FilterOnePerPair0.position = new Vector2(938f, 163);
            FilterAdjacentPair0.FixSeed = 0;
            FilterAdjacentPair0.position = new Vector2(1125f, 725);
            FilterByRoom0.RemoveMode = false;
            FilterByRoom0.Type1 = RoomType.Kitchen;
            FilterByRoom0.FilterSecond = true;
            FilterByRoom0.Type2 = RoomType.Dining;
            FilterByRoom0.FixSeed = 0;
            FilterByRoom0.position = new Vector2(800f, 750);
            AppendFeatures0.FixSeed = 0;
            AppendFeatures0.position = new Vector2(1813f, -137);
            SwitchFeatures0.SetToFeature = FeatureType.Hatch;
            SwitchFeatures0.FixSeed = 0;
            SwitchFeatures0.position = new Vector2(1475f, 713);
            RequireAccessible0.AllowGardens = false;
            RequireAccessible0.ResultStatus = true;
            RequireAccessible0.FixSeed = 0;
            RequireAccessible0.position = new Vector2(2200f, -162);
            RequireFeatures0.Type = FeatureType.Hatch;
            RequireFeatures0.Minimum = 2;
            RequireFeatures0.ResultStatus = true;
            RequireFeatures0.FixSeed = 0;
            RequireFeatures0.position = new Vector2(2575f, 13);
            SplitRooms0.UniformX = 2;
            SplitRooms0.UniformY = 2;
            SplitRooms0.RandomX = 1;
            SplitRooms0.RandomY = 2;
            SplitRooms0.FixSeed = 0;
            SplitRooms0.position = new Vector2(-1000f, -125);
            CreateRoomByJoins0.StartX = 3;
            CreateRoomByJoins0.StartY = 1;
            CreateRoomByJoins0.Joins = 2;
            CreateRoomByJoins0.Type = RoomType.Kitchen;
            CreateRoomByJoins0.Required = false;
            CreateRoomByJoins0.FixSeed = 0;
            CreateRoomByJoins0.position = new Vector2(-1700f, -12);
            CreateRoomByJoins1.StartX = 0;
            CreateRoomByJoins1.StartY = 0;
            CreateRoomByJoins1.Joins = 3;
            CreateRoomByJoins1.Type = RoomType.Dining;
            CreateRoomByJoins1.Required = false;
            CreateRoomByJoins1.FixSeed = 0;
            CreateRoomByJoins1.position = new Vector2(-1975f, -12);
            RoomGrid0.Width = 4;
            RoomGrid0.Height = 2;
            RoomGrid0.Type = RoomType.NoRoom;
            RoomGrid0.SetType = false;
            RoomGrid0.FixSeed = 0;
            RoomGrid0.position = new Vector2(-2325f, 0);
            AddRoom0.X = 2;
            AddRoom0.Y = 0;
            AddRoom0.Height = 1;
            AddRoom0.Width = 2;
            AddRoom0.Type = RoomType.Garden;
            AddRoom0.FixSeed = 0;
            AddRoom0.position = new Vector2(-1362f, -25);

            // Connecting all the nodes

            MergeRoomsByType0.GetPort("Input").Connect(SplitRooms0.GetPort("Output"));
            RecentreLayout0.GetPort("Input").Connect(MergeRoomsByType0.GetPort("Output"));
            CreateFrontDoor0.GetPort("Input").Connect(RecentreLayout0.GetPort("Output"));
            Output0.GetPort("Input").Connect(RequireAccessible0.GetPort("Output"));
            FindAllFeatures0.GetPort("Input").Connect(RecentreLayout0.GetPort("Output"));
            FilterByFreeSpace0.GetPort("Input").Connect(FindAllFeatures0.GetPort("Output"));
            FilterOnePerPair0.GetPort("Input").Connect(FilterByFreeSpace0.GetPort("Output"));
            FilterAdjacentPair0.GetPort("Input").Connect(FilterByRoom0.GetPort("Output"));
            FilterByRoom0.GetPort("Input").Connect(FindAllFeatures0.GetPort("Output"));
            AppendFeatures0.GetPort("AppendFrom").Connect(SwitchFeatures0.GetPort("Output"));
            AppendFeatures0.GetPort("AppendFrom").Connect(FilterOnePerPair0.GetPort("Output"));
            AppendFeatures0.GetPort("Input").Connect(CreateFrontDoor0.GetPort("Output"));
            SwitchFeatures0.GetPort("Input").Connect(FilterAdjacentPair0.GetPort("Output"));
            RequireAccessible0.GetPort("Input").Connect(AppendFeatures0.GetPort("Output"));
            RequireFeatures0.GetPort("Input").Connect(RequireAccessible0.GetPort("Output"));
            SplitRooms0.GetPort("Input").Connect(AddRoom0.GetPort("Output"));
            CreateRoomByJoins0.GetPort("Input").Connect(CreateRoomByJoins1.GetPort("Output"));
            CreateRoomByJoins1.GetPort("Input").Connect(RoomGrid0.GetPort("Output"));
            AddRoom0.GetPort("Input").Connect(CreateRoomByJoins0.GetPort("Output"));

            // Adding all the nodes to the graph and setting the graph

            graph.nodes.Add(MergeRoomsByType0);
            MergeRoomsByType0.graph = graph;
            graph.nodes.Add(RecentreLayout0);
            RecentreLayout0.graph = graph;
            graph.nodes.Add(CreateFrontDoor0);
            CreateFrontDoor0.graph = graph;
            graph.nodes.Add(Output0);
            Output0.graph = graph;
            graph.nodes.Add(FindAllFeatures0);
            FindAllFeatures0.graph = graph;
            graph.nodes.Add(FilterByFreeSpace0);
            FilterByFreeSpace0.graph = graph;
            graph.nodes.Add(FilterOnePerPair0);
            FilterOnePerPair0.graph = graph;
            graph.nodes.Add(FilterAdjacentPair0);
            FilterAdjacentPair0.graph = graph;
            graph.nodes.Add(FilterByRoom0);
            FilterByRoom0.graph = graph;
            graph.nodes.Add(AppendFeatures0);
            AppendFeatures0.graph = graph;
            graph.nodes.Add(SwitchFeatures0);
            SwitchFeatures0.graph = graph;
            graph.nodes.Add(RequireAccessible0);
            RequireAccessible0.graph = graph;
            graph.nodes.Add(RequireFeatures0);
            RequireFeatures0.graph = graph;
            graph.nodes.Add(SplitRooms0);
            SplitRooms0.graph = graph;
            graph.nodes.Add(CreateRoomByJoins0);
            CreateRoomByJoins0.graph = graph;
            graph.nodes.Add(CreateRoomByJoins1);
            CreateRoomByJoins1.graph = graph;
            graph.nodes.Add(RoomGrid0);
            RoomGrid0.graph = graph;
            graph.nodes.Add(AddRoom0);
            AddRoom0.graph = graph;
            graph.name = graphName;

            return graph;
        }


        public override void OnRegister(LayoutProfile gameDataObject)
        {
            base.OnRegister(gameDataObject);
            Registry.AddSettingLayout(GDOReferences.ParentsSetting, gameDataObject);
        }
    }
}